/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ArbitragePathService } from "../arbitragePath.service";
import { ArbitragePathCreateInput } from "./ArbitragePathCreateInput";
import { ArbitragePath } from "./ArbitragePath";
import { ArbitragePathFindManyArgs } from "./ArbitragePathFindManyArgs";
import { ArbitragePathWhereUniqueInput } from "./ArbitragePathWhereUniqueInput";
import { ArbitragePathUpdateInput } from "./ArbitragePathUpdateInput";
import { TradeFindManyArgs } from "../../trade/base/TradeFindManyArgs";
import { Trade } from "../../trade/base/Trade";
import { TradeWhereUniqueInput } from "../../trade/base/TradeWhereUniqueInput";

export class ArbitragePathControllerBase {
  constructor(protected readonly service: ArbitragePathService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ArbitragePath })
  async createArbitragePath(
    @common.Body() data: ArbitragePathCreateInput
  ): Promise<ArbitragePath> {
    return await this.service.createArbitragePath({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        tokenA: true,
        tokenB: true,
        tokenC: true,
        exchangeA: true,
        exchangeB: true,
        exchangeC: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ArbitragePath] })
  @ApiNestedQuery(ArbitragePathFindManyArgs)
  async arbitragePaths(
    @common.Req() request: Request
  ): Promise<ArbitragePath[]> {
    const args = plainToClass(ArbitragePathFindManyArgs, request.query);
    return this.service.arbitragePaths({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        tokenA: true,
        tokenB: true,
        tokenC: true,
        exchangeA: true,
        exchangeB: true,
        exchangeC: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ArbitragePath })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async arbitragePath(
    @common.Param() params: ArbitragePathWhereUniqueInput
  ): Promise<ArbitragePath | null> {
    const result = await this.service.arbitragePath({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        tokenA: true,
        tokenB: true,
        tokenC: true,
        exchangeA: true,
        exchangeB: true,
        exchangeC: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ArbitragePath })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateArbitragePath(
    @common.Param() params: ArbitragePathWhereUniqueInput,
    @common.Body() data: ArbitragePathUpdateInput
  ): Promise<ArbitragePath | null> {
    try {
      return await this.service.updateArbitragePath({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          tokenA: true,
          tokenB: true,
          tokenC: true,
          exchangeA: true,
          exchangeB: true,
          exchangeC: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ArbitragePath })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteArbitragePath(
    @common.Param() params: ArbitragePathWhereUniqueInput
  ): Promise<ArbitragePath | null> {
    try {
      return await this.service.deleteArbitragePath({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          tokenA: true,
          tokenB: true,
          tokenC: true,
          exchangeA: true,
          exchangeB: true,
          exchangeC: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/trades")
  @ApiNestedQuery(TradeFindManyArgs)
  async findTrades(
    @common.Req() request: Request,
    @common.Param() params: ArbitragePathWhereUniqueInput
  ): Promise<Trade[]> {
    const query = plainToClass(TradeFindManyArgs, request.query);
    const results = await this.service.findTrades(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        initialAmount: true,
        profit: true,
        timestamp: true,

        arbitragePath: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/trades")
  async connectTrades(
    @common.Param() params: ArbitragePathWhereUniqueInput,
    @common.Body() body: TradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trades: {
        connect: body,
      },
    };
    await this.service.updateArbitragePath({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/trades")
  async updateTrades(
    @common.Param() params: ArbitragePathWhereUniqueInput,
    @common.Body() body: TradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trades: {
        set: body,
      },
    };
    await this.service.updateArbitragePath({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/trades")
  async disconnectTrades(
    @common.Param() params: ArbitragePathWhereUniqueInput,
    @common.Body() body: TradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trades: {
        disconnect: body,
      },
    };
    await this.service.updateArbitragePath({
      where: params,
      data,
      select: { id: true },
    });
  }
}
